### ISSUE TITLE
OK so not an issue but I can't fathom out how to message you :(

### ISSUE THREAD

**Issue by emeyedeejay** [Quantiversal/Cape-Town-Loadshedding-Schedule#2]
Some seriously clever maths in that!

Have you fathomed a way or do you have a source for getting the loadshedding stage for the City of Cape town municipality? They are usually a stage better but that's a bit hit and miss for automation etc.

Thanks!

**Comment by Quantiversal** [comment]
Hey.

Unfortunately not. This repo is more about getting the table data once you have the stage. I just used EWN as an example.

It does suck that it's hard to get. I think even Eskom Se Push does everything manually to get the stage since they add custom messages every time. It would be nice if the government made a nice API to check the status reliably but after so many years of that not happening, we're on our own :(

**Comment by emeyedeejay** [comment]
Thought as much ... it would be handy but probably to only a fraction of the population so not on their "to do list" I wouldn't think.

Anyway - that's SA for you. Thanks for responding.

**Comment by Quantiversal** [comment]
Makes sense. Best of luck anyway 😀
